'use strict';
const $=s=>document.querySelector(s), form=$('#form'), key='atelie-propostas-v1';
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const item=()=>({name:'',description:'',quantity:1,unit:'un.',price:0,photo:''});
const defaults=()=>({id:crypto.randomUUID(),company:'',tagline:'Higienização de estofados e carpetes',email:'',phone:'',companyAddress:'',color:'#214e3a',logo:'',intro:'Atuamos na higienização de estofados e carpetes, com foco no cuidado dos tecidos e na conservação dos ambientes. Nossa proposta apresenta os serviços e as condições de atendimento para que você tenha clareza sobre cada etapa da contratação.',client:'',clientContact:'',address:'',number:`PROP-${today().replaceAll('-','')}-${Math.floor(100+Math.random()*900)}`,date:today(),validity:15,area:'',title:'Proposta de higienização de estofados e carpetes',discount:5,installments:4,benefits:'',notes:'',items:[item()]});
let state=defaults(), saved=[], dirty=false, timer;
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#toast').style.display='none',4500)}
try{saved=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(saved))saved=[]}catch{toast('Não foi possível ler o armazenamento local. Use o backup para guardar seus dados.')}
function refreshSaved(){const value=$('#saved').value;$('#saved').innerHTML='<option value="">Selecione para abrir</option>'+saved.map(s=>`<option value="${esc(s.id)}">${esc(s.number)} • ${esc(s.client||'Sem cliente')}</option>`).join('');$('#saved').value=value}
function fill(){for(const input of form.querySelectorAll('[name]'))input.value=state[input.name]??'';renderItems();render();dirty=false}
function renderItems(){$('#items').innerHTML=state.items.map((it,i)=>`<div class="item-card" data-index="${i}"><div class="item-head"><strong>ITEM ${String(i+1).padStart(2,'0')}</strong><button type="button" data-action="remove" class="quiet" aria-label="Excluir item ${i+1}">Excluir ×</button></div><div class="fields"><label class="wide">Item / estofado<input data-field="name" value="${esc(it.name)}" placeholder="Ex.: Cadeira estofada" required></label><label class="wide">Descrição do serviço<textarea data-field="description" rows="2" placeholder="Ex.: Higienização do assento e encosto">${esc(it.description)}</textarea></label><div class="item-numbers"><label>Quantidade<input data-field="quantity" type="number" min="0.01" max="1000000" step="0.01" value="${it.quantity}" required></label><label>Unidade<select data-field="unit"><option ${it.unit==='un.'?'selected':''}>un.</option><option ${it.unit==='m²'?'selected':''}>m²</option></select></label><label>Valor (R$)<input data-field="price" type="number" min="0" max="10000000" step="0.01" value="${it.price}" required></label></div><label class="wide">Foto do item<div class="photo-line">${it.photo?`<img src="${it.photo}" alt="Foto do item ${i+1}">`:''}<input type="file" data-photo accept="image/png,image/jpeg,image/webp"></div></label>${it.photo?'<button type="button" data-action="remove-photo" class="quiet">Remover foto</button>':''}</div></div>`).join('')}
function totals(s){const rows=s.items.map(it=>Math.round(Math.round(Number(it.price)*100)*Number(it.quantity)));const total=rows.reduce((a,b)=>a+b,0);const pix=Math.round(total*(1-Number(s.discount)/100));const count=Math.max(1,Math.trunc(Number(s.installments)||1));return {rows,total,pix,count,part:Math.floor(total/count),remainder:total%count}}
function dateLabel(v){return /^\d{4}-\d{2}-\d{2}$/.test(v)?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):''}
function render(){const s=state,t=totals(s),company=esc(s.company||'Sua empresa');const strip=`<div class="doc-strip"><span>${company.toUpperCase()}</span><span>PROPOSTA ${esc(s.number)} · ${dateLabel(s.date)}</span></div>`;const footer=`<footer class="doc-footer"><strong>${company}</strong><br>${[s.companyAddress,s.email,s.phone].filter(Boolean).map(esc).join(' · ')}</footer>`;const end=new Date(s.date+'T12:00:00');end.setDate(end.getDate()+Number(s.validity));const installment=t.remainder?`${t.remainder} parcela(s) de ${money(t.part+1)} e ${t.count-t.remainder} de ${money(t.part)}`:`Em ${t.count}x sem juros`;
$('#proposal').innerHTML=`<article class="sheet" style="--accent:${s.color}">${strip}<div class="doc-brand">${s.logo?`<img class="doc-logo" src="${s.logo}" alt="Logotipo da empresa">`:''}<h2>${company}</h2><p>${esc(s.tagline)}</p></div><h3 class="doc-title">${esc(s.title)}</h3><div class="client">${esc(s.client||'Nome do cliente')}</div><div class="client-info">${[s.address,s.clientContact].filter(Boolean).map(esc).join('<br>')}</div><p class="intro-text">${esc(s.intro)}</p><div class="scope-bar"><span>ESCOPO DOS SERVIÇOS</span><em>${esc(s.area||'Itens e ambientes')}</em></div><table class="service-table"><thead><tr><th>FOTO</th><th>DESCRIÇÃO DO SERVIÇO</th><th>QTD.</th><th>UNIT.</th><th>TOTAL</th></tr></thead><tbody>${s.items.map((it,i)=>`<tr><td>${it.photo?`<img src="${it.photo}" alt="${esc(it.name)}">`:'<span class="empty-photo">—</span>'}</td><td><strong>${esc(it.name||'Item a definir')}</strong><small>${esc(it.description)}</small></td><td>${Number(it.quantity).toLocaleString('pt-BR')} ${esc(it.unit)}</td><td>${money(Math.round(it.price*100))}</td><td>${money(t.rows[i])}</td></tr>`).join('')}</tbody></table>${footer}</article><article class="sheet" style="--accent:${s.color}">${strip}<div class="investment"><h3>INVESTIMENTO TOTAL</h3><div class="amount">${money(t.total)}</div></div><div class="payments"><div class="payment"><span>PIX</span><strong>${money(t.pix)}</strong><small>${Number(s.discount).toLocaleString('pt-BR')}% de desconto à vista</small></div><div class="payment"><span>CARTÃO</span><strong>${money(t.part+(t.remainder?1:0))} / parcela</strong><small>${installment}<br>Total: ${money(t.total)}</small></div></div>${s.benefits.trim()?`<h3 class="section-title">NOSSOS DIFERENCIAIS</h3><ul class="benefits">${s.benefits.split('\n').filter(x=>x.trim()).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${s.notes.trim()?`<h3 class="section-title">CONDIÇÕES DE ATENDIMENTO</h3><div class="notes">${esc(s.notes)}</div>`:''}<div class="validity"><strong>Validade da proposta</strong><br>Válida por ${esc(s.validity)} dias a partir da emissão, até ${Number.isNaN(end.getTime())?'—':end.toLocaleDateString('pt-BR')}.</div>${footer}</article>`}
form.addEventListener('input',e=>{if(e.target.name){state[e.target.name]=e.target.type==='number'?Number(e.target.value):e.target.value;dirty=true;render()}const field=e.target.dataset.field;if(field){const i=Number(e.target.closest('[data-index]').dataset.index);state.items[i][field]=['quantity','price'].includes(field)?Number(e.target.value):e.target.value;dirty=true;render()}});
$('#add').onclick=()=>{state.items.push(item());dirty=true;renderItems();render()};
$('#items').onclick=e=>{const action=e.target.dataset.action;if(!action)return;const i=Number(e.target.closest('[data-index]').dataset.index);if(action==='remove'){if(state.items.length===1)return toast('Mantenha pelo menos um serviço.');state.items.splice(i,1)}else state.items[i].photo='';dirty=true;renderItems();render()};
async function photo(file,preserveTransparency=false){if(!file)return '';if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Use uma imagem JPG, PNG ou WebP.');if(file.size>20*1024*1024)throw Error('A imagem deve ter no máximo 20 MB.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1000/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!preserveTransparency){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL(preserveTransparency?'image/png':'image/jpeg',0.82)}finally{URL.revokeObjectURL(url)}}
$('#items').addEventListener('change',async e=>{if(!e.target.hasAttribute('data-photo'))return;const target=state.items[Number(e.target.closest('[data-index]').dataset.index)];try{const result=await photo(e.target.files[0]);if(result&&state.items.includes(target)){target.photo=result;dirty=true;renderItems();render()}}catch(err){toast(err.message)}});
$('#logo').onchange=async e=>{const target=state;try{const result=await photo(e.target.files[0],true);if(result&&state===target){state.logo=result;dirty=true;render()}}catch(err){toast(err.message)}e.target.value=''};
$('#suggestIntro').onclick=()=>{state.intro=`${state.company.trim()||'Nossa empresa'} atua na higienização de estofados e carpetes, com foco no cuidado dos tecidos e na conservação dos ambientes. Nossa proposta apresenta os serviços e as condições de atendimento para que você tenha clareza sobre cada etapa da contratação.`;form.querySelector('[name=intro]').value=state.intro;dirty=true;render()};
$('#removeLogo').onclick=()=>{state.logo='';dirty=true;render()};
function valid(){if(!form.reportValidity())return false;if(state.items.length===0){toast('Adicione pelo menos um serviço.');return false}return true}
$('#save').onclick=()=>{if(!valid())return;const next=saved.filter(s=>s.id!==state.id);next.unshift(structuredClone(state));try{localStorage.setItem(key,JSON.stringify(next));saved=next;dirty=false;refreshSaved();$('#saved').value=state.id;toast('Orçamento salvo neste navegador.')}catch{toast('Não foi possível salvar. Exporte um backup para preservar o orçamento.')}};
function mayDiscard(){return !dirty||confirm('Há alterações não salvas. Deseja continuar sem salvar?')}
$('#new').onclick=()=>{if(!mayDiscard())return;const old=state;state=defaults();for(const k of ['company','tagline','email','phone','companyAddress','color','logo','intro','benefits','notes','discount','installments'])state[k]=old[k];fill();$('#saved').value='';toast('Nova proposta criada. Dados da empresa mantidos.')};
$('#open').onclick=()=>{const found=saved.find(s=>s.id===$('#saved').value);if(!found)return toast('Selecione um orçamento.');if(!mayDiscard())return;state=structuredClone(found);fill();toast('Orçamento aberto.')};
$('#delete').onclick=()=>{const id=$('#saved').value;if(!id)return toast('Selecione um orçamento.');if(!confirm('Excluir este orçamento do armazenamento do navegador?'))return;const next=saved.filter(s=>s.id!==id);try{localStorage.setItem(key,JSON.stringify(next));saved=next;refreshSaved();toast('Orçamento excluído.')}catch{toast('Não foi possível excluir o orçamento.')}};
$('#export').onclick=()=>{const payload={version:1,proposals:[structuredClone(state),...saved.filter(s=>s.id!==state.id)]};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`backup-propostas-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup gerado com a proposta atual e as propostas salvas.')};
function sanitize(raw){if(!raw||typeof raw!=='object'||!Array.isArray(raw.items)||!raw.items.length||raw.items.length>300)throw Error('Backup com estrutura inválida.');const clean=defaults();for(const k of Object.keys(clean)){if(typeof clean[k]==='string'&&typeof raw[k]==='string')clean[k]=raw[k].slice(0,10000)}clean.id=crypto.randomUUID();const image=v=>typeof v==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v)&&v.length<4000000?v:'';clean.logo=image(raw.logo);if(!/^#[0-9a-f]{6}$/i.test(clean.color))clean.color='#214e3a';if(!/^\d{4}-\d{2}-\d{2}$/.test(clean.date)||Number.isNaN(Date.parse(clean.date)))clean.date=today();const num=(v,min,max,fallback)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):fallback;clean.discount=num(raw.discount,0,100,0);clean.installments=Math.trunc(num(raw.installments,1,24,1));clean.validity=Math.trunc(num(raw.validity,1,365,15));clean.items=raw.items.map(it=>{if(!it||typeof it!=='object')throw Error('Item inválido no backup.');return {name:String(it.name||'').slice(0,1000),description:String(it.description||'').slice(0,10000),quantity:num(it.quantity,.01,1000000,1),price:num(it.price,0,10000000,0),unit:it.unit==='m²'?'m²':'un.',photo:image(it.photo)}});return clean}
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>40*1024*1024)throw Error('O backup deve ter até 40 MB.');const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.proposals)||!data.proposals.length||data.proposals.length>100)throw Error('Arquivo de backup inválido.');const incoming=data.proposals.map(sanitize);if(!mayDiscard())return;const next=[...incoming,...saved];localStorage.setItem(key,JSON.stringify(next));saved=next;state=structuredClone(incoming[0]);refreshSaved();fill();$('#saved').value=state.id;toast('Backup importado. Orçamentos anteriores preservados.')}catch(err){toast('Não foi possível importar: '+err.message)}finally{e.target.value=''}};
$('#print').onclick=async()=>{if(!valid())return;await Promise.all([...$('#proposal').querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));const old=document.title;document.title=`${state.number} - ${state.client}`;window.print();document.title=old};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
refreshSaved();fill();
