import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {createApp} from '../backend/app.js';import {modelo} from '../utils/proposta.js';import {settings as company,image} from './test-company.mjs';
import {googleFixture} from './google-fixture.mjs';import {defaultFinancialSettings,defaultEstimateInput} from '../backend/finance-domain.js';
import {resolveActual,simulate,allocate,metrics,accuracy,breakEven,priceForMargin,actualInput} from '../backend/profit-domain.js';
import {localDate,addMonths} from '../backend/dre-domain.js';import {profitDemo} from '../backend/profit-demo.js';
const recognition={proposalId:'x',revenue:50000,cost:12000,costSource:'estimated',costSnapshot:{materialCost:8000,travelCost:3000,otherDirectCosts:1000}};
const real=resolveActual(recognition,{version:1,input:{revenue:48000,material:9000,travel:4000,otherCosts:[{name:'Auxiliar',cents:1000}],minutes:120}});
assert.deepEqual([real.estimatedMargin,real.margin,real.costVariance,real.marginVariance],[38000,34000,2000,-4000]);
assert.equal(resolveActual(recognition,null).cost,12000);
assert.equal(resolveActual({...recognition,cost:null,costSnapshot:{materialCost:8000,travelCost:null,tollCost:1000,otherDirectCosts:0}},null).knownCost,9000);
const partial=resolveActual(recognition,{input:{material:10000}});assert.equal(partial.cost,14000);assert.equal(partial.costSource,'mixed');
assert.equal(resolveActual({...recognition,cost:null,costSnapshot:null},{input:{material:1}}).cost,null);
assert.equal(priceForMargin(10000,7500),40000);assert.equal(priceForMargin(11000,7000),36667);
assert.equal(simulate(15000,30000,7000,6000).belowMinimum,true);assert.equal(simulate(10000,40000,7500,6000).maximumDiscount,15000);
assert.equal(simulate(0,0,7000,6000).marginPercent,null);assert.throws(()=>priceForMargin(100,10000));assert.throws(()=>actualInput({minutes:0}));
assert.deepEqual(allocate(100,[1,1,1]),[34,33,33]);assert.deepEqual(allocate(-100,[1,1,1]),[-34,-33,-33]);
assert.equal(metrics([{proposalId:'a',revenue:10000,cost:0},{proposalId:'b',revenue:90000,cost:45000}]).marginPercent,55);
assert.equal(metrics([{proposalId:'a',revenue:48000,cost:14000,minutes:120}]).marginPerHour,17000);
assert.equal(accuracy([real,real])[2].sufficient,false);assert.equal(accuracy(Array(5).fill(real))[2].sufficient,true);
const bt={serviceCount:1,gross:1000000,cost:300000,deductions:0,variableExpenses:0,fixedExpenses:800000};
assert.equal(breakEven(bt,true).value,1142858);assert.equal(breakEven(bt,false).value,null);
const fixture=googleFixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'universal-profit-')),origin='http://localhost:3194';
let routes=0;const system=createApp({origin,dataDir:dir,fetcher:fixture.fetch,routeProvider:{id:'fixture',configured:true,route:()=>{routes++;throw Error('No routes in intelligence')}},googleConfig:{clientId:'fixture',clientSecret:'fixture',redirectURI:origin+'/api/google/callback'}});
const {repo,finance,dre,profit}=system,server=system.app.listen(3194,'127.0.0.1');await new Promise(r=>server.once('listening',r));let cookie='',csrf='';
async function request(url,body,method=body?'POST':'GET',headers={}){return fetch(origin+url,{method,headers:{Origin:origin,Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});}
async function data(url,body,method){const r=await request(url,body,method),v=await r.json();assert.equal(r.status,200,JSON.stringify(v));return v;}
const p='/api/profitability',m='2025-09';
try{
 for(const u of ['/report?from='+m+'&to='+m,'/settings','/goals/'+m,'/report.csv?from='+m+'&to='+m,'/demo?from='+m+'&to='+m])assert.equal((await request(p+u)).status,401);
 const setup=await request('/api/setup',{password:'profit-test-password'});cookie=setup.headers.get('set-cookie').split(';')[0];csrf=(await setup.json()).csrf;
 assert.equal((await request(p+'/settings')).status,428);await data('/api/onboarding',company);
 const defaults=await data(p+'/settings');assert.equal((await request(p+'/settings',{...defaults,targetBps:7500},'PUT',{'X-CSRF-Token':'bad'})).status,403);
 await data(p+'/settings',{...defaults,targetBps:7500,minimumBps:6000},'PUT');
 await data('/api/financial-settings',{...defaultFinancialSettings(),defaultMaterialBps:2000},'PUT');
 async function quote(id,contact='',price=500){let q=modelo.quote(company);Object.assign(q,{id,client:'Mesmo nome de teste',clientContact:contact,address:'Endereço sem cidade estruturada'});q.items=[{...modelo.item('Sofá'),price,photos:[image]}];q=await data('/api/proposals/'+id,q,'PUT');await data('/api/proposals/'+id+'/finance',{proposalRevision:q.revision,expectedVersion:0,inputs:{...defaultEstimateInput(),considerTravel:false,materialOverrideCents:12000}},'PUT');return q;}
 const q=await quote('profit-main','11999990000'),estimate=structuredClone(finance.latest(q.id)),ctx=profit.context(q.id);
 await data(p+'/proposals/'+q.id+'/context',{...ctx,city:'Santo André',state:'SP',estimatedMinutes:120},'PUT');
 let sim=await data(p+'/proposals/'+q.id+'/simulate',{price:30000});assert.equal(sim.belowMinimum,false);assert.equal(sim.referencePrice,48000);
 assert.equal(repo.requireProposal(q.id).items[0].price,500);
 assert.equal((await request(p+'/proposals/'+q.id+'/apply-price',{...sim,confirmedTotal:30000,confirm:false})).status,409);
 system.google.saveConnection({id:'profit-fixture',sub:'test-account',email:'agenda@example.invalid',calendarId:'primary',accessToken:'secret',refreshToken:'secret',expires:Date.now()+3600000});
 const scheduled=await data('/api/proposals/'+q.id+'/schedule',{key:crypto.randomUUID(),revision:q.revision,date:localDate(Date.now()+86400000),time:'09:00',duration:120});
 const eventBefore=JSON.stringify(fixture.events.get(scheduled.schedule.eventId)),pdf=repo.listPDFs(q.id)[0],pdfBytes=fs.readFileSync(repo.file(pdf)),publicBefore=await data('/api/proposals/'+q.id);
 repo.setOperation({...scheduled,schedule:{...scheduled.schedule,start:'2025-09-10T09:00:00-03:00',end:'2025-09-10T11:00:00-03:00'}});
 await data('/api/proposals/'+q.id+'/status',{status:'completed',serviceDate:'2025-09-10'});
 assert.equal(dre.report(m,m).total.cost,12000);
 const actual={expectedVersion:0,revenue:48000,material:9000,travel:4000,otherCosts:[{name:'Auxiliar',cents:1000}],minutes:120,notes:'PRIVATE_PROFIT_MARKER'};
 let v=await data(p+'/proposals/'+q.id+'/actual',actual,'PUT');assert.equal(v.comparison.margin,34000);assert.equal(v.comparison.costSource,'actual');
 let report=await data('/api/finance/report?from='+m+'&to='+m);assert.equal(report.total.gross,48000);assert.equal(report.total.cost,14000);assert.equal(report.total.actualCount,1);
 assert.deepEqual(finance.latest(q.id),estimate);assert.deepEqual(await data('/api/proposals/'+q.id),publicBefore);assert.deepEqual(fs.readFileSync(repo.file(pdf)),pdfBytes);assert.equal(JSON.stringify(fixture.events.get(scheduled.schedule.eventId)),eventBefore);
 assert.ok(!/PRIVATE_PROFIT_MARKER|actualCost|marginVariance|profitability/.test(JSON.stringify(await data('/api/backup'))));
 assert.equal((await request(p+'/proposals/'+q.id+'/actual',{...actual,expectedVersion:0,reason:'stale'},'PUT')).status,409);
 assert.equal((await request(p+'/proposals/'+q.id+'/actual',{...actual,expectedVersion:1},'PUT')).status,400);
 v=await data(p+'/proposals/'+q.id+'/actual',{...actual,expectedVersion:1,reason:'Corrigir consumo',material:11000},'PUT');assert.equal(v.history.length,2);assert.equal(v.history[1].input.material,9000);assert.equal(dre.report(m,m).total.cost,16000);assert.equal(profit.recognition(q.id).cost,12000);
 const missing=await quote('profit-partial');
 repo.setOperation({id:missing.id,status:'scheduled',schedule:{start:'2025-09-11T09:00:00-03:00',end:'2025-09-11T11:00:00-03:00'}});
 await system.service.status(missing.id,'completed',{serviceDate:'2025-09-11'});
 await data(p+'/proposals/'+missing.id+'/actual',{expectedVersion:0,material:13000},'PUT');
 assert.equal(dre.report(m,m).total.mixedCount,1);
 const fallback=await quote('profit-fallback','11999990000');
 repo.setOperation({id:fallback.id,status:'scheduled',schedule:{start:'2025-09-12T09:00:00-03:00',end:'2025-09-12T11:00:00-03:00'}});
 await system.service.status(fallback.id,'completed',{serviceDate:'2025-09-12'});assert.equal(dre.report(m,m).total.estimatedCount,1);
 let analytic=await data(p+'/report?from='+m+'&to='+m);assert.equal(analytic.summary.count,3);assert.equal(analytic.byClient.length,2);assert.equal(analytic.byCity.length,2);assert.equal(analytic.insights.length,0);assert.equal(analytic.references[0].reference,undefined);
 assert.equal(analytic.summary.marginPercent,Math.round((148000-41000)/148000*10000)/100);assert.equal(analytic.coverage.actualPercent,33.33);
 assert.equal((await data(p+'/report?'+new URLSearchParams({from:m,to:m,city:'Santo André / SP'}))).summary.count,1);
 assert.equal((await data(p+'/report?from='+m+'&to='+m+'&costSource=actual')).summary.count,1);
 const goal=await data(p+'/goals/'+m,{expectedVersion:0,revenue:100000,marginBps:6000,result:30000,ticket:40000},'PUT');assert.equal(goal.version,1);
 assert.equal((await request(p+'/goals/'+m,{expectedVersion:1,revenue:200000},'PUT')).status,400);
 await data(p+'/goals/'+m,{expectedVersion:1,revenue:200000,reason:'Novo objetivo'},'PUT');assert.equal(profit.goal('2025-08').values,null);
 const future=addMonths(localDate().slice(0,7),1),s=await data(p+'/settings');await data(p+'/settings',{...s,defaultGoals:{revenue:500000},goalsFrom:future},'PUT');assert.equal(profit.goal(future).values.revenue,500000);assert.equal(profit.goal(m).values.revenue,200000);
 const editable=await quote('profit-price','',300);const pricePdf=await system.service.generate(editable.id,{revision:editable.revision}),bytes=fs.readFileSync(repo.file(pricePdf));
 sim=await data(p+'/proposals/'+editable.id+'/simulate',{useReference:true});
 const applied=await data(p+'/proposals/'+editable.id+'/apply-price',{useReference:true,proposalRevision:sim.proposalRevision,estimateVersion:sim.estimateVersion,confirmedTotal:sim.appliedTotal,confirm:true});
 assert.equal(applied.quote.items[0].price,480);assert.deepEqual(fs.readFileSync(repo.file(pricePdf)),bytes);assert.equal(finance.view(editable.id).stale,true);
 assert.equal((await request(p+'/proposals/'+q.id+'/apply-price',{confirm:true})).status,409);
 const csv=await request(p+'/report.csv?from='+m+'&to='+m);assert.equal(csv.status,200);assert.ok((await csv.text()).includes('Custo real completo'));
 const exported=await data('/api/financial-export');assert.equal(exported.version,3);assert.equal(exported.actuals.length,3);assert.equal(exported.goals.length,2);
 const count=repo.list().length;const demo=await data(p+'/demo?from='+m+'&to='+m);assert.equal(demo.records.length,6);assert.equal(repo.list().length,count);assert.equal(demo.coverage.actual,6);assert.ok(demo.insights.length);assert.ok(demo.references.some(r=>r.count>=5&&r.reference>0));
 assert.equal(routes,0);
 // Reopening the repository must retain versions and actual priority.
 const previous=profit.recognition(q.id);assert.equal(previous.competence,m);assert.equal(profit.latest(q.id).version,2);
 assert.ok(repo.db.prepare("SELECT COUNT(*) n FROM finance_audit WHERE entity='actual'").get().n>=3);
 assert.equal((await request(p+'/report?from=2025-01&to=2027-12')).status,400);
 console.log('PASS: Fase 3 — cálculos, precisão, mínimo de amostra, agrupamentos, histórico, fallback, DRE, fluxo completo, metas, preços explícitos, exportações, auth/CSRF e privacidade PDF/Calendar.');
}finally{server.close();repo.close();}
