import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {createApp} from '../backend/app.js';
import {Repository,documentHash} from '../backend/database.js';
import {modelo} from '../utils/proposta.js';
import {googleFixture} from './google-fixture.mjs';
import {settings,image} from './test-company.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ecoclean-tests-')),origin='http://localhost:3198',fixture=googleFixture();
const system=createApp({origin,dataDir:dir,fetcher:fixture.fetch,googleConfig:{clientId:'test-client',clientSecret:'test-secret',redirectURI:origin+'/api/google/callback'}});
const server=system.app.listen(3198,'127.0.0.1');await new Promise(r=>server.once('listening',r));let cookie,csrf;
async function request(url,body,method=body?'POST':'GET',extra={}){return fetch(origin+url,{method,headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),'X-CSRF-Token':csrf||'','Content-Type':'application/json',...extra},body:body?JSON.stringify(body):undefined,redirect:'manual'})}
async function data(url,body,method){const r=await request(url,body,method),value=await r.json();assert.equal(r.status,200,JSON.stringify(value));return value}
try{
  assert.equal((await request('/api/proposals')).status,401);
  assert.equal((await request('/api/setup',{password:'ecoclean-test-password'},'POST',{Origin:'https://outside.invalid'})).status,403);
  const setup=await request('/api/setup',{password:'ecoclean-test-password'});assert.equal(setup.status,200);cookie=setup.headers.get('set-cookie').split(';')[0];csrf=(await setup.json()).csrf;
  assert.equal((await request('/api/settings',{},'PUT',{'X-CSRF-Token':'wrong'})).status,403);
  for(const url of ['/data/ecoclean.sqlite','/orcamentos/private.pdf','/%6frcamentos/private.pdf','/backend/app.js','/.env'])assert.equal((await request(url)).status,404,url);
  await data('/api/onboarding',settings);modelo.configure(settings);
  let q=modelo.quote(settings);q.client='Cliente de teste';q.address='Endereço de teste';q.items=[{...modelo.item('Sofá'),price:200,photos:[image]}];
  q=await data('/api/proposals/'+q.id,q,'PUT');assert.equal(q.revision,1);
  const other={...q,client:'Outra aba'};other.revision=0;assert.equal((await request('/api/proposals/'+q.id,other,'PUT')).status,409);
  await data('/api/draft',{id:'current',quote:q},'PUT');assert.equal((await data('/api/draft')).quote.client,q.client);
  let pdf=await data('/api/proposals/'+q.id+'/pdf',{revision:q.revision});assert.equal(pdf.version,1);assert.ok(!('storageKey'in pdf));const bytes=Buffer.from(await(await request(pdf.url)).arrayBuffer());assert.equal(bytes.subarray(0,5).toString(),'%PDF-');
  const key=()=>crypto.randomUUID(),date=new Date(Date.now()+7*86400000).toISOString().slice(0,10),input={key:key(),date,time:'09:00',duration:120,revision:q.revision};
  assert.equal((await request('/api/proposals/'+q.id+'/schedule',input)).status,503);assert.equal(system.repo.operation(q.id).status,'generated');
  const auth=await data('/api/google/connect',{}),state=new URL(auth.url).searchParams.get('state');assert.ok(new URL(auth.url).searchParams.get('code_challenge'));
  assert.equal((await request('/api/google/callback?state=wrong&code=x')).status,302);assert.equal((await request('/api/google/callback?state='+state+'&code=x')).status,302);
  assert.equal((await data('/api/google/status')).connected,true);assert.ok(!system.repo.config('google').includes('test-refresh-secret'));
  assert.equal((await request('/api/google/callback?state='+state+'&code=x')).headers.get('location').includes('google=error'),true);
  fixture.loseUpload=true;assert.equal((await request('/api/proposals/'+q.id+'/schedule',input)).status,502);assert.equal(fixture.files.size,2);assert.equal(system.repo.operation(q.id).status,'generated');
  fixture.loseEvent=true;assert.equal((await request('/api/proposals/'+q.id+'/schedule',input)).status,502);assert.equal(fixture.events.size,1);assert.equal(system.repo.operation(q.id).status,'generated');
  const confirmed=await data('/api/proposals/'+q.id+'/schedule',input);assert.equal(confirmed.status,'scheduled');assert.equal(fixture.events.size,1);assert.equal(fixture.files.size,2);
  assert.deepEqual(await data('/api/proposals/'+q.id+'/schedule',input),confirmed);
  const event=fixture.events.get(confirmed.schedule.eventId);assert.equal(event.location,q.address);assert.equal(event.attachments.length,1);assert.ok(!event.attendees);assert.ok(event.description.includes(q.client));
  const rescheduled=await data('/api/proposals/'+q.id+'/schedule',{...input,key:key(),time:'14:00'});assert.equal(rescheduled.schedule.eventId,confirmed.schedule.eventId);assert.equal(fixture.events.size,1);assert.equal(fixture.files.size,2);
  q=await data('/api/proposals/'+q.id,{...q,client:'Cliente atualizado'},'PUT');const pdf2=await data('/api/proposals/'+q.id+'/pdf',{revision:q.revision});assert.equal(pdf2.version,2);assert.deepEqual(Buffer.from(await(await request(pdf.url)).arrayBuffer()),bytes);
  assert.equal((await request('/api/proposals/'+q.id+'/schedule', {...input,key:key()})).status,409);
  await data('/api/proposals/'+q.id+'/schedule/cancel',{key:key()});assert.equal(fixture.events.size,0);assert.equal(system.repo.operation(q.id).status,'generated');
  const backup=await data('/api/backup');assert.equal(backup.documents.length,2);assert.ok(!JSON.stringify(backup).includes('test-refresh-secret'));
  const imported=await data('/api/import?migration=yes',backup);assert.equal(imported.imported,1);assert.equal((await data('/api/import?migration=yes',backup)).imported,0);
  assert.equal((await request('/api/import',{...backup,documents:[{...backup.documents[0],data:'invalid'}]})).status,400);assert.equal(system.repo.list().length,2);
  const q2=system.repo.proposal(imported.proposals[0].id);fixture.failEvent=true;assert.equal((await request('/api/proposals/'+q2.id+'/schedule',{...input,key:key(),revision:q2.revision})).status,502);assert.equal(system.repo.operation(q2.id).status,'generated');fixture.failEvent=false;
  const originalComplete=system.repo.complete.bind(system.repo);system.repo.complete=()=>{throw Error('Falha de confirmação no banco')};assert.equal((await request('/api/proposals/'+q2.id+'/schedule',{...input,key:key(),revision:q2.revision})).status,400);system.repo.complete=originalComplete;assert.equal(fixture.events.size,1);
  await data('/api/proposals/'+q2.id+'/schedule',{...input,key:key(),revision:q2.revision});assert.equal(fixture.events.size,1);
  const reopen=new Repository(dir);assert.equal(reopen.list().length,2);assert.equal(reopen.operation(q2.id).status,'scheduled');assert.equal(reopen.listPDFs(q.id).length,2);reopen.close();
  await data('/api/logout',{});assert.equal((await request(pdf.url)).status,401);
  console.log('PASS: autenticação, CSRF, arquivos privados, SQLite, revisões, PDFs imutáveis, OAuth, Drive, agenda, recuperação, reagendamento, cancelamento, backup e migração.');
}finally{await new Promise(r=>server.close(r));system.repo.close()}
