import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {createApp} from '../backend/app.js';
import {modelo} from '../utils/proposta.js';
import {settings as company,image} from './test-company.mjs';
import {googleFixture} from './google-fixture.mjs';
import {defaultFinancialSettings,defaultEstimateInput} from '../backend/finance-domain.js';
import {aggregate,month,date,addMonths,localDate,ratio,variation,expenseInput} from '../backend/dre-domain.js';
import {DreService} from '../backend/dre-service.js';
import {csvCell} from '../backend/dre-export.js';
const fixture=googleFixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'universal-dre-')),origin='http://localhost:3195';
let routeCalls=0;
const system=createApp({origin,dataDir:dir,fetcher:fixture.fetch,routeProvider:{id:'fixture',configured:true,route:()=>{routeCalls++;throw Error('DRE must not request routes');}},googleConfig:{clientId:'test-client',clientSecret:'test-secret',redirectURI:origin+'/api/google/callback'}});
const {repo,dre,finance}=system,server=system.app.listen(3195,'127.0.0.1');await new Promise(r=>server.once('listening',r));let cookie='',csrf='';
async function request(url,body,method=body?'POST':'GET',headers={}){return fetch(origin+url,{method,headers:{Origin:origin,Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});}
async function data(url,body,method){const r=await request(url,body,method),v=await r.json();assert.equal(r.status,200,JSON.stringify(v));return v;}
const query=(m,mode='actual')=>'/api/finance/report?'+new URLSearchParams({from:m,to:m,mode});
const standard=aggregate([{revenue:1000000,cost:200000,costSource:'estimated'}],[{amountCents:400000,nature:'operating',costType:'fixed'}],{rateBps:600,manualCents:null});
assert.deepEqual([standard.gross,standard.deductions,standard.net,standard.contribution,standard.result,standard.operatingMargin],[1000000,60000,940000,740000,340000,36.17]);
assert.equal(aggregate([],[],{rateBps:0}).operatingMargin,null);assert.equal(ratio(-100,200),-50);assert.equal(variation(10,0),null);assert.equal(variation(-50,-100),50);
assert.throws(()=>month('2025-13'));assert.throws(()=>date('2025-02-30'));assert.throws(()=>expenseInput({description:'x',amountCents:1,competence:'2025-09',status:'paid'}));assert.ok(csvCell('=HYPERLINK("x")').startsWith('"\'='));assert.ok(csvCell(' @SUM(1)').startsWith('"\''));
try{
 for(const path of ['/api/finance/report','/api/finance/expenses','/api/finance/report.pdf','/api/finance/report.csv','/api/finance/demo'])assert.equal((await request(path)).status,401);
 const setup=await request('/api/setup',{password:'dre-test-password'});cookie=setup.headers.get('set-cookie').split(';')[0];csrf=(await setup.json()).csrf;
 assert.equal((await request('/api/finance/settings')).status,428);await data('/api/onboarding',company);
 assert.equal((await request('/api/finance/settings',{taxRateBps:600},'PUT',{'X-CSRF-Token':'wrong'})).status,403);
 const financial={...defaultFinancialSettings(),defaultMaterialBps:2000};
 await data('/api/financial-settings',financial,'PUT');await data('/api/finance/settings',{taxRateBps:600,vehicleComponents:['maintenance']},'PUT');
 let q=modelo.quote(company);q.client='Cliente DRE fictício';q.address='Endereço de teste';q.items=[{...modelo.item('Sofá'),price:10000,photos:[image]}];
 q=await data('/api/proposals/'+q.id,q,'PUT');await data('/api/proposals/'+q.id+'/finance',{proposalRevision:q.revision,expectedVersion:0,inputs:{...defaultEstimateInput(),considerTravel:false}},'PUT');
 const snapshot=finance.latest(q.id);assert.equal((await data(query('2025-09'))).total.gross,0);
 system.google.saveConnection({id:'dre-fixture',sub:'test-account',email:'agenda@example.invalid',calendarId:'primary',accessToken:'test-access-secret',refreshToken:'test-refresh-secret',expires:Date.now()+3600000});
 const tomorrow=localDate(Date.now()+86400000),scheduled=await data('/api/proposals/'+q.id+'/schedule',{key:crypto.randomUUID(),revision:q.revision,date:tomorrow,time:'09:00',duration:120});
 const event=fixture.events.get(scheduled.schedule.eventId);assert.ok(!/finance|margin|costSnapshot|materialCost|custo|margem|deduction/i.test(JSON.stringify(event)));
 const projected=await data(query(tomorrow.slice(0,7),'projected'));assert.equal(projected.total.gross,1000000);assert.equal((await data(query(tomorrow.slice(0,7)))).total.gross,0);
 const pdf=repo.listPDFs(q.id)[0],before=fs.readFileSync(repo.file(pdf));
 // Simulates an appointment whose execution has now passed; Google remains a local fixture.
 repo.setOperation({...scheduled,schedule:{...scheduled.schedule,start:'2025-09-30T12:00:00-03:00',end:'2025-09-30T14:00:00-03:00'}});
 const done=await data('/api/proposals/'+q.id+'/status',{status:'completed',serviceDate:'2025-09-30'});assert.equal(done.serviceCompletedAt,'2025-09-30');
 await data('/api/proposals/'+q.id+'/status',{status:'completed',serviceDate:'2025-09-30'});assert.equal(repo.db.prepare('SELECT COUNT(*) n FROM finance_recognitions').get().n,1);
 assert.equal((await request('/api/proposals/'+q.id+'/schedule/cancel',{key:crypto.randomUUID()})).status,409);
 repo.setOperation({...repo.operation(q.id),paidAt:'2025-10-03'});assert.equal((await data(query('2025-10'))).total.gross,0);
 const category=(await data('/api/finance/categories'))[0];
 const makeExpense=(over={})=>({description:'Despesa teste',categoryId:category.id,amountCents:400000,competence:'2025-09',status:'paid',paidAt:'2025-10-03',nature:'operating',costType:'fixed',...over});
 let exp=await data('/api/finance/expenses',makeExpense());
 await data('/api/finance/prepare',{from:'2025-09',to:'2025-10'});
 let report=await data(query('2025-09'));assert.deepEqual([report.total.gross,report.total.deductions,report.total.net,report.total.cost,report.total.contribution,report.total.opex,report.total.result,report.total.operatingMargin],[1000000,60000,940000,200000,740000,400000,340000,36.17]);
 assert.equal((await data(query('2025-10'))).total.opex,0);
 const confirmed=await data('/api/finance/expenses',makeExpense({description:'Não paga',amountCents:1000,status:'confirmed',paidAt:null}));
 const planned=await data('/api/finance/expenses',makeExpense({description:'Prevista',amountCents:2000,status:'planned',paidAt:null}));
 const investment=await data('/api/finance/expenses',makeExpense({description:'Equipamento',amountCents:500000,nature:'investment'}));
 report=await data(query('2025-09'));assert.equal(report.total.opex,401000);assert.equal(report.total.investment,500000);
 assert.equal((await data(query('2025-09','projected'))).total.opex,403000);assert.equal((await data(query('2025-09','projected'))).total.gross,1000000);
 await data('/api/financial-settings',{...financial,defaultMaterialBps:9900},'PUT');assert.equal((await data(query('2025-09'))).total.cost,200000);assert.deepEqual(finance.latest(q.id),snapshot);
 await data('/api/finance/settings',{taxRateBps:1000,vehicleComponents:['maintenance']},'PUT');assert.equal((await data(query('2025-09'))).total.taxCents,60000);
 let tax=(await data(query('2025-09'))).periods[0].tax;
 assert.equal((await request('/api/finance/tax/2025-09',{source:'manual',manualCents:30000,revision:tax.revision},'PUT')).status,400);
 tax=await data('/api/finance/tax/2025-09',{source:'manual',manualCents:30000,revision:tax.revision,confirm:true,reason:'Apuração informada'},'PUT');
 report=await data(query('2025-09'));assert.equal(report.total.taxCents,30000);assert.equal(report.total.taxEstimated,60000);assert.equal(report.periods[0].tax.originalRateBps,600);
 assert.equal((await request('/api/finance/expenses/'+exp.id,{...exp,amountCents:1,revision:0,reason:'teste'},'PUT')).status,409);
 exp=await data('/api/finance/expenses/'+exp.id,{...exp,status:'cancelled',paidAt:null,reason:'Cancelamento teste'},'PUT');assert.equal((await data(query('2025-09'))).total.opex,1000);
 assert.equal((await request('/api/finance/expenses/'+exp.id,{...exp,status:'paid',reason:'Reativar'},'PUT')).status,409);
 const warn=await data('/api/finance/expenses',makeExpense({amountCents:10,vehicleComponent:'maintenance'}));assert.equal(warn.warnings.length,1);
 const deduction=await data('/api/finance/expenses',makeExpense({description:'Estorno',amountCents:5000,nature:'deduction',deductionType:'refund'}));assert.equal((await data(query('2025-09'))).total.otherDeductions,5000);
 assert.equal((await request('/api/finance/expenses',makeExpense({nature:'deduction',deductionType:'other',notes:''}))).status,400);
 const cat2=await data('/api/finance/categories',{name:'Categoria nova'});await data('/api/finance/categories/'+cat2.id,{...cat2,active:false},'PUT');assert.equal((await request('/api/finance/expenses',makeExpense({categoryId:cat2.id}))).status,400);
 const renamed=await data('/api/finance/categories/'+category.id,{...category,name:'Renomeada'},'PUT');assert.equal((await data('/api/finance/expenses?from=2025-09&to=2025-09')).items[0].categoryId,renamed.id);
 // Recurrences: unique occurrences, future-only price revisions, recognized history retained.
 const first=localDate().slice(0,7),second=addMonths(first,1),third=addMonths(first,2);
 let rule=await data('/api/finance/recurrences',{effectiveMonth:first,frequency:'monthly',dueDay:31,template:makeExpense({description:'Recorrente',amountCents:35000,status:'planned',paidAt:null})});
 await data('/api/finance/prepare',{from:first,to:third});await data('/api/finance/prepare',{from:first,to:third});
 assert.equal(repo.db.prepare('SELECT COUNT(*) n FROM finance_expenses WHERE rule_id=?').get(rule.id).n,3);
 rule=await data('/api/finance/recurrences/'+rule.id,{revision:rule.revision,effectiveMonth:third,frequency:'monthly',dueDay:31,template:{...rule.versions[0].template,amountCents:40000}},'PUT');
 const occurrences=repo.db.prepare('SELECT data FROM finance_expenses WHERE rule_id=? ORDER BY competence').all(rule.id).map(r=>JSON.parse(r.data));
 assert.deepEqual(occurrences.map(e=>e.amountCents),[35000,35000,40000]);
 const paidRule=await data('/api/finance/expenses/'+occurrences[2].id,{...occurrences[2],status:'paid',paidAt:localDate(),reason:'Pagamento antecipado'},'PUT');
 await data('/api/finance/recurrences/'+rule.id,{revision:rule.revision,effectiveMonth:third,frequency:'monthly',dueDay:31,template:{...rule.versions[0].template,amountCents:45000}},'PUT');assert.equal(dre.getExpense(paidRule.id).amountCents,40000);
 const annual=await data('/api/finance/recurrences',{effectiveMonth:first,frequency:'annual',dueDay:31,template:makeExpense({amountCents:120000,status:'planned',paidAt:null})});await data('/api/finance/prepare',{from:first,to:addMonths(first,12)});assert.equal(repo.db.prepare('SELECT COUNT(*) n FROM finance_expenses WHERE rule_id=?').get(annual.id).n,2);
 const missing=modelo.quote(company);missing.client='Sem custo';missing.address='Teste';missing.items=[{...modelo.item('Sofá'),price:200}];repo.saveProposal(missing);repo.setOperation({id:missing.id,status:'completed',schedule:null,serviceCompletedAt:'2025-08-12'});
 new DreService(repo,finance);let gap=await data(query('2025-08'));assert.equal(gap.total.gross,20000);assert.equal(gap.total.cost,null);assert.equal(gap.total.result,null);assert.equal(gap.total.missingCosts,1);
 repo.setOperation({id:missing.id,status:'cancelled'});assert.equal((await data(query('2025-08'))).total.gross,0);
 for(let i=0;i<21;i++)await data('/api/finance/expenses',makeExpense({description:'Pagina '+i,amountCents:1,competence:'2025-07'}));
 const paged=await data('/api/finance/expenses?from=2025-07&to=2025-07&page=2&search=Pagina');assert.equal(paged.total,21);assert.equal(paged.items.length,1);
 const exports=await data('/api/financial-export');assert.equal(exports.version,3);for(const k of ['categories','recurrences','expenses','recognitions','periods','audit'])assert.ok(exports[k].length,k);
 const commercial=await data('/api/backup');assert.ok(!JSON.stringify(commercial).includes('costSnapshot'));assert.ok(!('expenses'in commercial));
 const reportPdf=await request('/api/finance/report.pdf?from=2025-09&to=2025-09');assert.equal(reportPdf.status,200);assert.equal(Buffer.from(await reportPdf.arrayBuffer()).subarray(0,5).toString(),'%PDF-');
 const csv=await request('/api/finance/report.csv?from=2025-09&to=2025-09');assert.ok((await csv.text()).includes('DRE GERENCIAL'));
 assert.deepEqual(fs.readFileSync(repo.file(pdf)),before);assert.equal(routeCalls,0);
 // Boundary periods and legacy completion without a usable date must remain reviewable.
 assert.equal((await data(query('2000-01'))).comparison.from,null);
 const legacy=modelo.quote(company);legacy.client='Legado sem data';legacy.address='Teste';legacy.items=[{...modelo.item('Sofá'),price:100}];repo.saveProposal(legacy);repo.setOperation({id:legacy.id,status:'completed',schedule:null,serviceCompletedAt:'1999-12-31'});
 new DreService(repo,finance);assert.ok((await data(query('2025-06'))).missingDates.some(s=>s.id===legacy.id));
 await data('/api/finance/realization/'+legacy.id,{serviceDate:'2025-06-30',reason:'Data conferida no registro do serviço'});assert.equal((await data(query('2025-06'))).total.gross,10000);
 assert.equal((await request('/api/finance/realization/'+legacy.id,{serviceDate:'2025-07-01',reason:'Duplicar'})).status,409);
 const countBefore=repo.db.prepare('SELECT COUNT(*) n FROM finance_expenses').get().n;await data('/api/finance/demo?from=2025-08&to=2025-10&mode=projected');assert.equal(repo.db.prepare('SELECT COUNT(*) n FROM finance_expenses').get().n,countBefore);
 await data('/api/logout',{});assert.equal((await request('/api/finance/report?from=2025-09&to=2025-09')).status,401);
 console.log('PASS: DRE por competência, fluxo orçamento/agenda/conclusão, cálculos, snapshots, despesas, recorrências, impostos, investimentos, paginação, privacidade e exportações.');
}finally{await new Promise(r=>server.close(r));repo.close();}
